add the access tier resource
banyansecurity/terraform-provider-banyan pull request #49
Opened 2022-11-03 20:31 UTC by TheMattSchiller

2022-11-08 15:05 UTC, danielboros requested changes

2022-11-09 00:57 UTC, TheMattSchiller commented on banyan/resource_accesstier.go
> +	c := m.(*client.Holder)
this is just how the terraform SDK implements CRUD functions

2022-11-09 00:59 UTC, TheMattSchiller commented on banyan/resource_accesstier.go
> +			ValidateFunc: validation.IntInSlice([]int{100, 1000, 5000}),
typically you will have validation for the state and validation which is done when submitting to the API. These parameters will need to be reviewed in both places when updates are made to the access tier

2022-11-09 03:58 UTC, danielboros approved these changes

2022-11-09 10:26 UTC, merged